name    'cumuluslinux-netdev_stdlib_cumulus_linux'
version '0.0.1'
source 'https://github.com/CumulusNetworks/puppet-netdev-stdlib-cumulus-linux'
author 'Sergey Sudakovich, Cumulus Networks'
license 'Apache License, Version 2.0'
summary 'Cumulus Linux netdev stdlib'
description 'Netdev provides a set of network resource abstractions for automating network device configuration using Puppet, this provider code is specific to Cumulus Linux.'
project_page 'https://github.com/CumulusNetworks/puppet-netdev-stdlib-cumulus-linux'

dependency 'netdevops/netdev_stdlib', '>= 1.0.0'
